import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import BaseLayout from '../layouts/BaseLayout'
import styles from '../styles/Home.module.css'

export function Segs() {
  const [clicked, setClicked] = useState(3);
  return (
    <div className="App">
      <button onClick={() => setClicked((clicked - 1) * 2)}>Henlo</button>
      <h1>{clicked}</h1>
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
      <Segs/>
          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>
      </div>
    </BaseLayout>
  )
}

export default Home
